services:
  users-db:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
    networks:
      - ilia-code-challenge
    volumes:
      - users-db:/data/db

  users:
    build: .
    image: bigsonlvrocha/ilia-code-challenge-users
    environment:
      MONGODB_URI: mongodb://users-db:27017
      PUBLIC_API_JWT_SECRET: ILIACHALLENGE
      PRIVATE_API_JWT_SECRET: ILIACHALLENGE_IN
      TRANSACTIONS_SERVICE_URL: http://transactions:3003
    ports:
      - 3002:3002
    depends_on:
      - users-db
    networks:
      - ilia-code-challenge


networks:
  ilia-code-challenge:
    driver: bridge
    name: ilia-code-challenge

volumes:
  users-db:
